### ISSUE TITLE
.exe doesnt work

### ISSUE THREAD

**Issue by Nyanekoy** [duke7553/files-uwp#128]
i saw on issue #12  that you should be able to run .exe however i tried and it doesnt seem to work. im on the v0.5.0-newui_snapshot2 version. or is it only working for older versions?

**Comment by duke7553** [comment]
Does the exe require admin access. Some that do won’t work.

**Comment by Nyanekoy** [comment]
no

**Comment by Nyanekoy** [comment]
ok so i just tried the other versions: 
0.4.8 Working
every other version does not

**Comment by duke7553** [comment]
Thanks. I will take a look then.

**Comment by duke7553** [comment]
Fixed in master. Please re-open if this breaks again.

**Comment by Lolihunter1337** [comment]
i have the windows store version 0.6.2.0 and .exe doesnt work for me as well

**Comment by yaichenbaum** [comment]
The fix should be included in the next update, if you build from the source code here then you should already have the issue fixed.

**Comment by SOI7** [comment]
I'm very sorry to revive this issue, but sadly I still can't open .exe files 😥

**Comment by yaichenbaum** [comment]
We are tracking this on #244.
