### ISSUE TITLE
Apparently not able to use folders in another drive as replacements for Music and Videos

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#474]
**Describe the bug**
I have my songs and videos in another HDD that isn't C:, but when I change the path of common locations in Files it ignores the new paths and still opens the Music and Videos folders in C:

**To Reproduce**
Go to Settings, enable "Replace common locations", change the default path of Music/Videos to another folder that isn't in C:

**Desktop:**
 - Windows 10 1909
 - App version: v0.7.2.0

**Additional context**
In the Settings view, those paths don't have the drive initial letter, unlike those located in C:, however OneDrive doesn't seem to be affected

![image](https://user-images.githubusercontent.com/50930970/77225815-2090e800-6b73-11ea-860c-15291709b234.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by yaichenbaum** [comment]
@SOI7 What happens if instead of replacing the locations from the settings page in Files UWP, you change the actual library location in Windows? This should fix the issue and will also make sure you have a consistent experience with file dialogs throughout other applications in Windows.

**Comment by SOI7** [comment]
I can't do that. I have an SSD with limited GBs as my OS drive and an external HDD for bigger files, so I always try to have all my non necessary files on the HDD

**Comment by yaichenbaum** [comment]
You don't need to move the files, from Files Explorer you can set a custom location for the library folders and Files UWP with automatically use that new location.
![image](https://user-images.githubusercontent.com/39923744/78294911-2d112b00-74f9-11ea-9dc2-b09ae14e7eaa.png)

**Comment by SOI7** [comment]
Ah, now I see. Then let me test this

**Comment by SOI7** [comment]
Changing the save location for libraries, like that article suggested, doesn't solve the issue. Files still uses the Library stored in C:

**Comment by yaichenbaum** [comment]
Did you turn off the setting to use custom locations in the settings page of Files UWP?

**Comment by SOI7** [comment]
Yeah

**Comment by yaichenbaum** [comment]
There is a potential fix coming in v0.7.3 but you will need to reset the app to test it. Sorry about the inconvenience.

**Comment by yaichenbaum** [comment]
@SOI7 Can you check if this is resolved with v0.7.4?

**Comment by SOI7** [comment]
Could you upload an installer package, please? I uninstalled the UWP definitions for Visual Studio because they take so much space and it's not worth it to keep them on my disk just to install an app now and then

**Comment by yaichenbaum** [comment]
@SOI7 The store is already up to v0.7.5 so you should be able to test from there.

**Comment by SOI7** [comment]
@yair100 Updated to 0.7.5. The option to change default Favorites location is gone from Settings... am I doing something wrong? As it is now, Favorites folders still redirect me to those in C:

**Comment by yaichenbaum** [comment]
@SOI7 If you reset the app, does it take you to the correct location?

**Comment by SOI7** [comment]
Nope, still C:
Also, now OneDrive shows my educational account folder instead of the personal one

**Comment by yaichenbaum** [comment]
Which directories is it not detecting right?

**Comment by SOI7** [comment]
Videos and OneDrive atm

**Comment by SOI7** [comment]
I need also to clarify that those are the only ones besides Music that I have on my secondary HDD, so I can't tell atm if the other Favorites are working properly or not since I can't manually change the default folders in Files anymore

**Comment by yaichenbaum** [comment]
@SOI7 Can you check if the paths in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders` match what you set in File Explorer?

**Comment by SOI7** [comment]
Well, surprisingly they don't. Videos, for example, is %USERPROFILE%\Videos instead of E:\Videos

**Comment by SOI7** [comment]
Changing the parameter in Regedit solved the issue in Files. I'd still bring custom locations back, though, but that's up to you

**Comment by yaichenbaum** [comment]
We don't plan on bringing it back as that would require the app modifying the registry, however at some point we will try to get the app to launch the File Explorer dialog's for changing the paths.
